
name: Test os226

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        test:
          - batch
          - syscall
          - cosched

    steps:
    - uses: actions/checkout@v2
    - run: make
    - run: ./test/run.sh test/${{matrix.test}}
